# ── AegisVersion.cmake ───────────────────────────────────────────────────
# Single source of truth: VERSION file
file(READ "${CMAKE_SOURCE_DIR}/VERSION" AEGIS_VERSION_STRING)
string(STRIP "${AEGIS_VERSION_STRING}" AEGIS_VERSION_STRING)
message(STATUS "aegis ${AEGIS_VERSION_STRING}")

project(aegis VERSION ${AEGIS_VERSION_STRING})

string(REPLACE "." ";" _AEGIS_VER_LIST ${AEGIS_VERSION_STRING})
list(GET _AEGIS_VER_LIST 0 AEGIS_VERSION_MAJOR)
list(GET _AEGIS_VER_LIST 1 AEGIS_VERSION_MINOR)
list(GET _AEGIS_VER_LIST 2 AEGIS_VERSION_PATCH)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
