# ── AegisTests.cmake ─────────────────────────────────────────────────────
if(AEGIS_BUILD_TESTS)
    enable_testing()
    find_package(GTest QUIET)
    if(NOT GTest_FOUND)
        message(STATUS "GTest not found; compiling GoogleTest as subproject")
        include(FetchContent)
        FetchContent_Declare(
            googletest
            GIT_REPOSITORY https://github.com/google/googletest.git
            GIT_TAG        v1.14.0
        )
        set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
        FetchContent_MakeAvailable(googletest)
    endif()

    add_executable(unit_scheduler tests/unit/test_scheduler.c)
    target_link_libraries(unit_scheduler PRIVATE aegis_scheduler GTest::gtest_main)
    aegis_set_warnings(unit_scheduler)
    add_test(NAME unit_scheduler COMMAND unit_scheduler)
    add_executable(unit_error tests/unit/common/test_error.c)
    target_link_libraries(unit_error PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_error)
    add_test(NAME unit_error COMMAND unit_error)
    add_executable(unit_allocator tests/unit/common/test_allocator.c)
    target_link_libraries(unit_allocator PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_allocator)
    add_test(NAME unit_allocator COMMAND unit_allocator)
    add_executable(unit_queue tests/unit/common/test_queue.c)
    target_link_libraries(unit_queue PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_queue)
    add_test(NAME unit_queue COMMAND unit_queue)
    add_executable(unit_hashmap tests/unit/common/test_hashmap.c)
    target_link_libraries(unit_hashmap PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_hashmap)
    add_test(NAME unit_hashmap COMMAND unit_hashmap)
    add_executable(unit_buffer tests/unit/common/test_buffer.c)
    target_link_libraries(unit_buffer PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_buffer)
    add_test(NAME unit_buffer COMMAND unit_buffer)
    add_executable(unit_string tests/unit/common/test_string.c)
    target_link_libraries(unit_string PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_string)
    add_test(NAME unit_string COMMAND unit_string)
    add_executable(unit_mutex tests/unit/common/test_mutex.c)
    target_link_libraries(unit_mutex PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_mutex)
    add_test(NAME unit_mutex COMMAND unit_mutex)
    add_executable(unit_uuid tests/unit/common/test_uuid.c)
    target_link_libraries(unit_uuid PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_uuid)
    add_test(NAME unit_uuid COMMAND unit_uuid)
    add_executable(unit_atomic tests/unit/common/test_atomic.c)
    target_link_libraries(unit_atomic PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_atomic)
    add_test(NAME unit_atomic COMMAND unit_atomic)
    add_executable(unit_vector tests/unit/common/test_vector.c)
    target_link_libraries(unit_vector PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_vector)
    add_test(NAME unit_vector COMMAND unit_vector)
    add_executable(unit_list tests/unit/common/test_list.c)
    target_link_libraries(unit_list PRIVATE aegis_common GTest::gtest_main)
    aegis_set_warnings(unit_list)
    add_test(NAME unit_list COMMAND unit_list)
    add_executable(unit_runtime tests/unit/test_runtime.c)
    target_link_libraries(unit_runtime PRIVATE aegis_runtime GTest::gtest_main)
    aegis_set_warnings(unit_runtime)
    add_test(NAME unit_runtime COMMAND unit_runtime)
    add_executable(unit_runtime_concurrent tests/unit/test_runtime_concurrent.c)
    target_link_libraries(unit_runtime_concurrent PRIVATE aegis_runtime GTest::gtest_main)
    aegis_set_warnings(unit_runtime_concurrent)
    add_test(NAME unit_runtime_concurrent COMMAND unit_runtime_concurrent)
    add_executable(unit_agent tests/unit/test_agent.c)
    target_link_libraries(unit_agent PRIVATE aegis_agent GTest::gtest_main)
    aegis_set_warnings(unit_agent)
    add_test(NAME unit_agent COMMAND unit_agent)
    add_executable(unit_agent_events tests/unit/test_agent_events.c)
    target_link_libraries(unit_agent_events PRIVATE aegis_agent GTest::gtest_main)
    aegis_set_warnings(unit_agent_events)
    add_test(NAME unit_agent_events COMMAND unit_agent_events)
    add_executable(unit_loop_strategy tests/unit/test_loop_strategy.c)
    target_link_libraries(unit_loop_strategy PRIVATE aegis_agent aegis_autonomous GTest::gtest_main)
    aegis_set_warnings(unit_loop_strategy)
    add_test(NAME unit_loop_strategy COMMAND unit_loop_strategy)
    add_executable(unit_agent_concurrent tests/unit/test_agent_concurrent.c)
    target_link_libraries(unit_agent_concurrent PRIVATE aegis_agent GTest::gtest_main)
    aegis_set_warnings(unit_agent_concurrent)
    add_test(NAME unit_agent_concurrent COMMAND unit_agent_concurrent)
    add_executable(unit_event_bus tests/unit/test_event_bus.c)
    target_link_libraries(unit_event_bus PRIVATE aegis_event GTest::gtest_main)
    aegis_set_warnings(unit_event_bus)
    add_test(NAME unit_event_bus COMMAND unit_event_bus)
    add_executable(unit_task tests/unit/test_task.c)
    target_link_libraries(unit_task PRIVATE aegis_task GTest::gtest_main)
    aegis_set_warnings(unit_task)
    add_test(NAME unit_task COMMAND unit_task)
    add_executable(unit_task_graph tests/unit/test_task_graph.c)
    target_link_libraries(unit_task_graph PRIVATE aegis_task GTest::gtest_main)
    aegis_set_warnings(unit_task_graph)
    add_test(NAME unit_task_graph COMMAND unit_task_graph)
    add_executable(unit_task_race_regression tests/unit/test_task_race_regression.c)
    target_link_libraries(unit_task_race_regression PRIVATE aegis_task GTest::gtest_main)
    aegis_set_warnings(unit_task_race_regression)
    add_test(NAME unit_task_race_regression COMMAND unit_task_race_regression)
    add_executable(unit_task_concurrent tests/unit/test_task_concurrent.c)
    target_link_libraries(unit_task_concurrent PRIVATE aegis_task GTest::gtest_main)
    aegis_set_warnings(unit_task_concurrent)
    add_test(NAME unit_task_concurrent COMMAND unit_task_concurrent)
    add_executable(unit_scheduler_concurrent tests/unit/test_scheduler_concurrent.c)
    target_link_libraries(unit_scheduler_concurrent PRIVATE aegis_scheduler GTest::gtest_main)
    aegis_set_warnings(unit_scheduler_concurrent)
    add_test(NAME unit_scheduler_concurrent COMMAND unit_scheduler_concurrent)
    add_executable(unit_executor tests/unit/test_executor.c)
    target_link_libraries(unit_executor PRIVATE aegis_executor GTest::gtest_main)
    aegis_set_warnings(unit_executor)
    add_test(NAME unit_executor COMMAND unit_executor)
    add_executable(unit_executor_concurrent tests/unit/test_executor_concurrent.c)
    target_link_libraries(unit_executor_concurrent PRIVATE aegis_executor GTest::gtest_main)
    aegis_set_warnings(unit_executor_concurrent)
    add_test(NAME unit_executor_concurrent COMMAND unit_executor_concurrent)
    add_executable(unit_tool tests/unit/test_tool.c)
    target_link_libraries(unit_tool PRIVATE aegis_tool GTest::gtest_main)
    aegis_set_warnings(unit_tool)
    add_test(NAME unit_tool COMMAND unit_tool)
    add_executable(unit_tool_executor tests/unit/test_tool_executor.c)
    target_link_libraries(unit_tool_executor PRIVATE aegis_tool aegis_executor aegis_task GTest::gtest_main)
    aegis_set_warnings(unit_tool_executor)
    add_test(NAME unit_tool_executor COMMAND unit_tool_executor)
    add_executable(unit_tool_concurrent tests/unit/test_tool_concurrent.c)
    target_link_libraries(unit_tool_concurrent PRIVATE aegis_tool aegis_executor aegis_task GTest::gtest_main)
    aegis_set_warnings(unit_tool_concurrent)
    add_test(NAME unit_tool_concurrent COMMAND unit_tool_concurrent)
    add_executable(unit_discovery_tools tests/unit/test_discovery_tools.c)
    target_link_libraries(unit_discovery_tools PRIVATE aegis_coding aegis_tool GTest::gtest_main)
    aegis_set_warnings(unit_discovery_tools)
    add_test(NAME unit_discovery_tools COMMAND unit_discovery_tools)
    add_executable(unit_git_tools tests/unit/test_git_tools.c)
    target_link_libraries(unit_git_tools PRIVATE aegis_coding aegis_tool GTest::gtest_main)
    aegis_set_warnings(unit_git_tools)
    add_test(NAME unit_git_tools COMMAND unit_git_tools)
    add_executable(unit_coding_agent tests/unit/test_coding_agent.c)
    target_link_libraries(unit_coding_agent PRIVATE aegis_coding GTest::gtest_main)
    aegis_set_warnings(unit_coding_agent)
    add_test(NAME unit_coding_agent COMMAND unit_coding_agent)
    add_executable(unit_provider tests/unit/test_provider.c)
    target_link_libraries(unit_provider PRIVATE aegis_provider GTest::gtest_main)
    aegis_set_warnings(unit_provider)
    add_test(NAME unit_provider COMMAND unit_provider)
    add_executable(unit_context tests/unit/test_context.c)
    target_link_libraries(unit_context PRIVATE aegis_context GTest::gtest_main)
    aegis_set_warnings(unit_context)
    add_test(NAME unit_context COMMAND unit_context)
    add_executable(unit_message tests/unit/test_message.c)
    target_link_libraries(unit_message PRIVATE aegis_message GTest::gtest_main)
    aegis_set_warnings(unit_message)
    add_test(NAME unit_message COMMAND unit_message)
    add_executable(unit_session tests/unit/test_session.c)
    target_link_libraries(unit_session PRIVATE aegis_session aegis_model GTest::gtest_main)
    aegis_set_warnings(unit_session)
    add_test(NAME unit_session COMMAND unit_session)
    add_executable(unit_mcp_json tests/unit/test_mcp_json.c)
    target_link_libraries(unit_mcp_json PRIVATE aegis_json aegis_common)
    target_include_directories(unit_mcp_json PRIVATE ${PROJECT_SOURCE_DIR}/src/mcp)
    aegis_set_warnings(unit_mcp_json)
    add_test(NAME unit_mcp_json COMMAND unit_mcp_json)
    add_executable(unit_delegate_tools tests/unit/test_delegate_tools.c)
    target_link_libraries(unit_delegate_tools PRIVATE aegis_coding aegis_agent aegis_session aegis_model aegis_tool aegis_common pthread)
    target_include_directories(unit_delegate_tools PRIVATE ${PROJECT_SOURCE_DIR}/src/mcp)
    aegis_set_warnings(unit_delegate_tools)
    add_test(NAME unit_delegate_tools COMMAND unit_delegate_tools)
    if(AEGIS_MCP)
        add_executable(mock_mcp_server tests/fixtures/mock_mcp_server.c)
        target_link_libraries(mock_mcp_server PRIVATE aegis_json)
        target_include_directories(mock_mcp_server PRIVATE ${PROJECT_SOURCE_DIR}/src/mcp)
        aegis_set_warnings(mock_mcp_server)
        add_executable(unit_mcp_client tests/unit/test_mcp_client.c)
        target_link_libraries(unit_mcp_client PRIVATE aegis_mcp aegis_tool aegis_json aegis_common)
        target_include_directories(unit_mcp_client PRIVATE ${PROJECT_SOURCE_DIR}/src/mcp)
        aegis_set_warnings(unit_mcp_client)
        add_test(NAME unit_mcp_client COMMAND unit_mcp_client)
        set_tests_properties(unit_mcp_client PROPERTIES ENVIRONMENT "MOCK_MCP_SERVER=${CMAKE_BINARY_DIR}/mock_mcp_server")
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(unit_mcp_client PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
    endif()
    add_executable(unit_storage tests/unit/test_storage.c)
    target_link_libraries(unit_storage PRIVATE aegis_storage aegis_provider GTest::gtest_main)
    aegis_set_warnings(unit_storage)
    add_test(NAME unit_storage COMMAND unit_storage)
    add_executable(unit_memory tests/unit/test_memory.c)
    target_link_libraries(unit_memory PRIVATE aegis_memory GTest::gtest_main)
    aegis_set_warnings(unit_memory)
    add_test(NAME unit_memory COMMAND unit_memory)
    add_executable(unit_skill_loader tests/unit/test_skill_loader.c)
    target_link_libraries(unit_skill_loader PRIVATE aegis_skill GTest::gtest_main)
    aegis_set_warnings(unit_skill_loader)
    add_test(NAME unit_skill_loader COMMAND unit_skill_loader)
    add_executable(unit_checkpoint tests/unit/test_checkpoint.c)
    target_link_libraries(unit_checkpoint PRIVATE aegis_checkpoint aegis_agent aegis_planner aegis_task GTest::gtest_main)
    aegis_set_warnings(unit_checkpoint)
    add_test(NAME unit_checkpoint COMMAND unit_checkpoint)
    add_executable(unit_log tests/unit/test_log.c)
    target_link_libraries(unit_log PRIVATE aegis_observability GTest::gtest_main)
    aegis_set_warnings(unit_log)
    add_test(NAME unit_log COMMAND unit_log)
    add_executable(unit_metrics tests/unit/test_metrics.c)
    target_link_libraries(unit_metrics PRIVATE aegis_observability GTest::gtest_main)
    aegis_set_warnings(unit_metrics)
    add_test(NAME unit_metrics COMMAND unit_metrics)
    add_executable(unit_trace tests/unit/test_trace.c)
    target_link_libraries(unit_trace PRIVATE aegis_observability GTest::gtest_main)
    aegis_set_warnings(unit_trace)
    add_test(NAME unit_trace COMMAND unit_trace)
    add_executable(unit_plugin tests/unit/test_plugin.c)
    target_link_libraries(unit_plugin PRIVATE aegis_plugin dl pthread GTest::gtest_main)
    aegis_set_warnings(unit_plugin)
    add_test(NAME unit_plugin COMMAND unit_plugin)
    add_executable(unit_security tests/unit/test_security.c)
    target_link_libraries(unit_security PRIVATE aegis_security pthread GTest::gtest_main)
    aegis_set_warnings(unit_security)
    add_test(NAME unit_security COMMAND unit_security)
    add_executable(unit_provider_llm tests/unit/test_provider_llm.c)
    target_link_libraries(unit_provider_llm PRIVATE aegis_provider GTest::gtest_main)
    aegis_set_warnings(unit_provider_llm)
    add_test(NAME unit_provider_llm COMMAND unit_provider_llm)
    add_executable(unit_provider_storage tests/unit/test_provider_storage.c)
    target_link_libraries(unit_provider_storage PRIVATE aegis_provider aegis_storage GTest::gtest_main)
    aegis_set_warnings(unit_provider_storage)
    add_test(NAME unit_provider_storage COMMAND unit_provider_storage)
    add_executable(unit_provider_embedding tests/unit/test_provider_embedding.c)
    target_link_libraries(unit_provider_embedding PRIVATE aegis_provider GTest::gtest_main)
    aegis_set_warnings(unit_provider_embedding)
    add_test(NAME unit_provider_embedding COMMAND unit_provider_embedding)
    add_executable(unit_provider_interfaces tests/unit/test_provider_interfaces.c)
    target_link_libraries(unit_provider_interfaces PRIVATE aegis_provider aegis_storage)
    aegis_set_warnings(unit_provider_interfaces)
    add_test(NAME unit_provider_interfaces COMMAND unit_provider_interfaces)
    add_executable(unit_planner_llm tests/unit/test_planner_llm.c)
    target_link_libraries(unit_planner_llm PRIVATE aegis_planner aegis_provider aegis_task aegis_critic GTest::gtest_main)
    aegis_set_warnings(unit_planner_llm)
    add_test(NAME unit_planner_llm COMMAND unit_planner_llm)
    add_executable(unit_strategy tests/unit/test_strategy.c)
    target_link_libraries(unit_strategy PRIVATE aegis_planner aegis_provider aegis_critic)
    aegis_set_warnings(unit_strategy)
    add_test(NAME unit_strategy COMMAND unit_strategy)
    add_executable(unit_planner tests/unit/test_planner.c)
    target_link_libraries(unit_planner PRIVATE aegis_planner aegis_executor aegis_task aegis_critic)
    aegis_set_warnings(unit_planner)
    add_test(NAME unit_planner COMMAND unit_planner)
    add_executable(system_autonomous tests/system/test_autonomous_closed_loop.c)
    target_link_libraries(system_autonomous PRIVATE aegis_autonomous aegis_provider GTest::gtest_main pthread)
    aegis_set_warnings(system_autonomous)
    add_test(NAME system_autonomous COMMAND system_autonomous)
    add_executable(system_autonomous_strategy tests/system/test_autonomous_strategy_e2e.c)
    target_link_libraries(system_autonomous_strategy PRIVATE aegis_autonomous aegis_agent aegis_session aegis_model aegis_provider GTest::gtest_main pthread)
    aegis_set_warnings(system_autonomous_strategy)
    add_test(NAME system_autonomous_strategy COMMAND system_autonomous_strategy)
    add_executable(unit_autonomous_tool tests/unit/test_autonomous_tool_integration.c)
    target_link_libraries(unit_autonomous_tool PRIVATE aegis_autonomous aegis_provider aegis_security aegis_tool GTest::gtest_main)
    aegis_set_warnings(unit_autonomous_tool)
    add_test(NAME unit_autonomous_tool COMMAND unit_autonomous_tool)
    add_executable(system_recovery_e2e tests/system/test_autonomous_recovery_e2e.c)
    target_link_libraries(system_recovery_e2e PRIVATE aegis_autonomous aegis_checkpoint aegis_provider aegis_tool GTest::gtest_main pthread)
    aegis_set_warnings(system_recovery_e2e)
    add_test(NAME system_recovery_e2e COMMAND system_recovery_e2e)
    add_executable(system_tool_e2e tests/system/test_autonomous_tool_e2e.c)
    target_link_libraries(system_tool_e2e PRIVATE aegis_autonomous aegis_provider aegis_tool GTest::gtest_main pthread)
    aegis_set_warnings(system_tool_e2e)
    add_test(NAME system_tool_e2e COMMAND system_tool_e2e)
    add_executable(system_security_e2e tests/system/test_autonomous_security_e2e.c)
    target_link_libraries(system_security_e2e PRIVATE aegis_autonomous aegis_provider aegis_security aegis_tool GTest::gtest_main pthread)
    aegis_set_warnings(system_security_e2e)
    add_test(NAME system_security_e2e COMMAND system_security_e2e)
    add_executable(system_cancellation_e2e tests/system/test_autonomous_cancellation_e2e.c)
    target_link_libraries(system_cancellation_e2e PRIVATE aegis_autonomous aegis_provider aegis_tool GTest::gtest_main pthread)
    aegis_set_warnings(system_cancellation_e2e)
    add_test(NAME system_cancellation_e2e COMMAND system_cancellation_e2e)
    add_executable(system_failure_e2e tests/system/test_autonomous_failure_e2e.c)
    target_link_libraries(system_failure_e2e PRIVATE aegis_autonomous aegis_provider aegis_tool GTest::gtest_main pthread)
    aegis_set_warnings(system_failure_e2e)
    add_test(NAME system_failure_e2e COMMAND system_failure_e2e)
    add_executable(stress_agent_loop tests/stress/test_agent_loop_stress.c)
    target_link_libraries(stress_agent_loop PRIVATE aegis_agent aegis_session aegis_model pthread)
    add_test(NAME stress_agent_loop COMMAND stress_agent_loop)
    add_executable(system_coding_loop tests/system/test_coding_loop.c)
    target_link_libraries(system_coding_loop PRIVATE aegis_agent aegis_message aegis_model aegis_session aegis_tool pthread)
    add_test(NAME system_coding_loop COMMAND system_coding_loop)
    if(AEGIS_ENABLE_ASAN)
        add_test(NAME asan_ctest_config
                 COMMAND ${CMAKE_COMMAND}
                         -DCTEST_FILE=${CMAKE_BINARY_DIR}/CTestTestfile.cmake
                         -P ${PROJECT_SOURCE_DIR}/tests/cmake/test_asan_ctest_config.cmake)
        set_tests_properties(asan_ctest_config PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        set_tests_properties(
            unit_scheduler unit_error unit_allocator unit_queue unit_hashmap unit_buffer unit_string
            unit_mutex unit_uuid unit_atomic unit_vector unit_list unit_runtime unit_runtime_concurrent
            unit_agent unit_agent_events unit_loop_strategy unit_agent_concurrent unit_event_bus unit_task unit_task_graph unit_task_race_regression
            unit_task_concurrent unit_scheduler_concurrent unit_executor unit_executor_concurrent unit_tool
            unit_tool_executor unit_tool_concurrent unit_discovery_tools unit_git_tools unit_coding_agent unit_provider unit_context unit_message unit_session
            unit_storage unit_memory unit_skill_loader unit_checkpoint unit_log unit_metrics unit_trace unit_plugin unit_security
            unit_provider_llm unit_provider_storage unit_provider_embedding unit_provider_interfaces unit_planner_llm unit_strategy unit_planner system_autonomous system_autonomous_strategy unit_autonomous_tool
            system_recovery_e2e system_tool_e2e system_security_e2e system_cancellation_e2e system_failure_e2e
            stress_agent_loop system_coding_loop
            PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
    endif()
    if(AEGIS_OPENAI_PROVIDER)
        add_executable(system_openai_multi_tool_e2e tests/system/test_openai_multi_tool_e2e.c)
        target_include_directories(system_openai_multi_tool_e2e PRIVATE ${PROJECT_SOURCE_DIR}/providers/llm/openai)
        target_link_libraries(system_openai_multi_tool_e2e PRIVATE aegis_llm_openai pthread)
        aegis_set_warnings(system_openai_multi_tool_e2e)
        add_test(NAME system_openai_multi_tool_e2e COMMAND system_openai_multi_tool_e2e)
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(system_openai_multi_tool_e2e PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
        add_executable(system_openai_tool_loop_e2e tests/system/test_openai_tool_loop_e2e.c)
        target_include_directories(system_openai_tool_loop_e2e PRIVATE ${PROJECT_SOURCE_DIR}/providers/llm/openai)
        target_link_libraries(system_openai_tool_loop_e2e PRIVATE aegis_llm_openai aegis_agent aegis_session aegis_message aegis_model aegis_tool pthread)
        aegis_set_warnings(system_openai_tool_loop_e2e)
        add_test(NAME system_openai_tool_loop_e2e COMMAND system_openai_tool_loop_e2e)
        add_executable(system_openai_http_status_e2e tests/system/test_openai_http_status_e2e.c)
        target_include_directories(system_openai_http_status_e2e PRIVATE ${PROJECT_SOURCE_DIR}/providers/llm/openai)
        target_link_libraries(system_openai_http_status_e2e PRIVATE aegis_llm_openai aegis_agent aegis_session aegis_model pthread)
        aegis_set_warnings(system_openai_http_status_e2e)
        add_test(NAME system_openai_http_status_e2e COMMAND system_openai_http_status_e2e)
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(system_openai_http_status_e2e PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(system_openai_tool_loop_e2e PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
        add_executable(system_openai_sse_e2e tests/system/test_openai_sse_e2e.c)
        target_include_directories(system_openai_sse_e2e PRIVATE ${PROJECT_SOURCE_DIR}/providers/llm/openai)
        target_link_libraries(system_openai_sse_e2e PRIVATE aegis_llm_openai pthread)
        aegis_set_warnings(system_openai_sse_e2e)
        add_test(NAME system_openai_sse_e2e COMMAND system_openai_sse_e2e)
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(system_openai_sse_e2e PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
        add_executable(unit_structured_openai tests/unit/test_structured_openai.c)
        target_include_directories(unit_structured_openai PRIVATE ${PROJECT_SOURCE_DIR}/providers/llm/openai)
        target_link_libraries(unit_structured_openai PRIVATE aegis_llm_openai)
        aegis_set_warnings(unit_structured_openai)
        add_test(NAME unit_structured_openai COMMAND unit_structured_openai)
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(unit_structured_openai PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
    endif()
    if(AEGIS_ANTHROPIC_PROVIDER)
        add_executable(system_anthropic_multi_tool_e2e tests/system/test_anthropic_tool_loop_e2e.c)
        target_include_directories(system_anthropic_multi_tool_e2e PRIVATE ${PROJECT_SOURCE_DIR}/providers/llm/anthropic)
        target_link_libraries(system_anthropic_multi_tool_e2e PRIVATE aegis_llm_anthropic aegis_agent aegis_session aegis_message aegis_model aegis_tool pthread)
        aegis_set_warnings(system_anthropic_multi_tool_e2e)
        add_test(NAME system_anthropic_multi_tool_e2e COMMAND system_anthropic_multi_tool_e2e)
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(system_anthropic_multi_tool_e2e PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
        add_executable(system_anthropic_http_status_e2e tests/system/test_anthropic_http_status_e2e.c)
        target_include_directories(system_anthropic_http_status_e2e PRIVATE ${PROJECT_SOURCE_DIR}/providers/llm/anthropic)
        target_link_libraries(system_anthropic_http_status_e2e PRIVATE aegis_llm_anthropic aegis_agent aegis_session aegis_model pthread)
        aegis_set_warnings(system_anthropic_http_status_e2e)
        add_test(NAME system_anthropic_http_status_e2e COMMAND system_anthropic_http_status_e2e)
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(system_anthropic_http_status_e2e PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
        add_executable(system_anthropic_sse_e2e tests/system/test_anthropic_sse_e2e.c)
        target_include_directories(system_anthropic_sse_e2e PRIVATE ${PROJECT_SOURCE_DIR}/providers/llm/anthropic)
        target_link_libraries(system_anthropic_sse_e2e PRIVATE aegis_llm_anthropic pthread)
        aegis_set_warnings(system_anthropic_sse_e2e)
        add_test(NAME system_anthropic_sse_e2e COMMAND system_anthropic_sse_e2e)
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(system_anthropic_sse_e2e PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
        add_executable(unit_structured_anthropic tests/unit/test_structured_anthropic.c)
        target_include_directories(unit_structured_anthropic PRIVATE ${PROJECT_SOURCE_DIR}/providers/llm/anthropic)
        target_link_libraries(unit_structured_anthropic PRIVATE aegis_llm_anthropic)
        aegis_set_warnings(unit_structured_anthropic)
        add_test(NAME unit_structured_anthropic COMMAND unit_structured_anthropic)
        if(AEGIS_ENABLE_ASAN)
            set_tests_properties(unit_structured_anthropic PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        endif()
    endif()
    add_executable(integration_cli tests/integration/test_cli.c)
    if(AEGIS_OPENAI_PROVIDER)
        target_compile_definitions(integration_cli PRIVATE AEGIS_OPENAI_PROVIDER)
        target_link_libraries(integration_cli PRIVATE pthread)
    endif()
    add_test(NAME integration_cli COMMAND integration_cli)
    add_executable(fuzz_session_standalone tests/fuzz/fuzz_session.c)
    target_compile_definitions(fuzz_session_standalone PRIVATE FUZZ_STANDALONE)
    target_link_libraries(fuzz_session_standalone PRIVATE aegis_session aegis_message aegis_common)
    aegis_set_warnings(fuzz_session_standalone)
    add_test(NAME fuzz_session_standalone COMMAND fuzz_session_standalone)
    if(AEGIS_ENABLE_ASAN)
        set_tests_properties(integration_cli PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
        set_tests_properties(fuzz_session_standalone PROPERTIES ENVIRONMENT "LD_PRELOAD=;ASAN_OPTIONS=verify_asan_link_order=0")
    endif()
endif()

# ── Mock plugin ─────────────────────────────────────────────────────────
add_library(mock_plugin SHARED tests/plugin/plugin_mock.c)
target_include_directories(mock_plugin PRIVATE ${PROJECT_SOURCE_DIR}/include
                                                ${PROJECT_SOURCE_DIR}/src/internal)
target_link_libraries(mock_plugin PRIVATE aegis_plugin)
set_target_properties(mock_plugin PROPERTIES
    LIBRARY_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/tests/plugin"
)

# ── Benchmarks ──────────────────────────────────────────────────────────
if(AEGIS_BUILD_BENCH)
    find_package(benchmark QUIET)
    if(NOT benchmark_FOUND)
        message(STATUS "google/benchmark not found; skipping benchmarks")
    else()
        add_executable(bench_scheduler benchmarks/bench_scheduler.c)
        target_link_libraries(bench_scheduler PRIVATE aegis_scheduler benchmark::benchmark)
        aegis_set_warnings(bench_scheduler)
    endif()
endif()
