# ── AegisTests.cmake ─────────────────────────────────────────────────────
if(AEGIS_BUILD_TESTS)
    enable_testing()
    find_package(GTest QUIET)
    if(NOT GTest_FOUND)
        message(STATUS "GTest not found; compiling GoogleTest as subproject")
        include(FetchContent)
        FetchContent_Declare(
            googletest
            GIT_REPOSITORY https://github.com/google/googletest.git
            GIT_TAG        v1.14.0
        )
        set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
        FetchContent_MakeAvailable(googletest)
    endif()

    macro(aegis_add_test name)
        add_executable(${name} ${ARGN})
        target_link_libraries(${name} PRIVATE aegis_core GTest::gtest_main)
        aegis_set_warnings(${name})
        add_test(NAME ${name} COMMAND ${name})
    endmacro()

    aegis_add_test(unit_scheduler  tests/unit/test_scheduler.c)
    aegis_add_test(unit_error      tests/unit/common/test_error.c)
    aegis_add_test(unit_allocator  tests/unit/common/test_allocator.c)
    aegis_add_test(unit_queue      tests/unit/common/test_queue.c)
    aegis_add_test(unit_hashmap    tests/unit/common/test_hashmap.c)
    aegis_add_test(unit_buffer     tests/unit/common/test_buffer.c)
    aegis_add_test(unit_string     tests/unit/common/test_string.c)
    aegis_add_test(unit_mutex      tests/unit/common/test_mutex.c)
    aegis_add_test(unit_uuid       tests/unit/common/test_uuid.c)
    aegis_add_test(unit_atomic     tests/unit/common/test_atomic.c)
    aegis_add_test(unit_vector     tests/unit/common/test_vector.c)
    aegis_add_test(unit_list       tests/unit/common/test_list.c)
    aegis_add_test(unit_runtime        tests/unit/test_runtime.c)
    aegis_add_test(unit_runtime_concurrent tests/unit/test_runtime_concurrent.c)
    aegis_add_test(unit_agent        tests/unit/test_agent.c)
    aegis_add_test(unit_agent_concurrent tests/unit/test_agent_concurrent.c)
    aegis_add_test(unit_event_bus        tests/unit/test_event_bus.c)
    aegis_add_test(unit_task             tests/unit/test_task.c)
    aegis_add_test(unit_task_graph       tests/unit/test_task_graph.c)
    aegis_add_test(unit_task_race_regression tests/unit/test_task_race_regression.c)
    aegis_add_test(unit_task_concurrent  tests/unit/test_task_concurrent.c)
    aegis_add_test(unit_scheduler_concurrent tests/unit/test_scheduler_concurrent.c)
    aegis_add_test(unit_executor             tests/unit/test_executor.c)
    aegis_add_test(unit_executor_concurrent  tests/unit/test_executor_concurrent.c)
    aegis_add_test(unit_tool             tests/unit/test_tool.c)
    aegis_add_test(unit_tool_executor    tests/unit/test_tool_executor.c)
    aegis_add_test(unit_tool_concurrent  tests/unit/test_tool_concurrent.c)
    aegis_add_test(unit_provider             tests/unit/test_provider.c)
    aegis_add_test(unit_context            tests/unit/test_context.c)
    aegis_add_test(unit_message            tests/unit/test_message.c)
    aegis_add_test(unit_session            tests/unit/test_session.c)
    aegis_add_test(unit_storage            tests/unit/test_storage.c)
    aegis_add_test(unit_memory             tests/unit/test_memory.c)
    aegis_add_test(unit_checkpoint         tests/unit/test_checkpoint.c)
    aegis_add_test(unit_log                tests/unit/test_log.c)
    aegis_add_test(unit_metrics            tests/unit/test_metrics.c)
    aegis_add_test(unit_trace              tests/unit/test_trace.c)
    aegis_add_test(unit_plugin             tests/unit/test_plugin.c)
    target_link_libraries(unit_plugin PRIVATE aegis_core dl pthread)
    aegis_add_test(unit_security           tests/unit/test_security.c)
    target_link_libraries(unit_security PRIVATE pthread)
    aegis_add_test(unit_provider_llm       tests/unit/test_provider_llm.c)
    aegis_add_test(unit_provider_storage   tests/unit/test_provider_storage.c)
    aegis_add_test(unit_provider_embedding tests/unit/test_provider_embedding.c)
    aegis_add_test(system_autonomous        tests/system/test_autonomous_closed_loop.c)
    target_link_libraries(system_autonomous PRIVATE pthread)
    aegis_add_test(unit_autonomous_tool tests/unit/test_autonomous_tool_integration.c)
    aegis_add_test(system_recovery_e2e tests/system/test_autonomous_recovery_e2e.c)
    target_link_libraries(system_recovery_e2e PRIVATE pthread)
    aegis_add_test(system_tool_e2e tests/system/test_autonomous_tool_e2e.c)
    target_link_libraries(system_tool_e2e PRIVATE pthread)
    aegis_add_test(system_security_e2e tests/system/test_autonomous_security_e2e.c)
    target_link_libraries(system_security_e2e PRIVATE pthread)
    aegis_add_test(system_cancellation_e2e tests/system/test_autonomous_cancellation_e2e.c)
    target_link_libraries(system_cancellation_e2e PRIVATE pthread)
    aegis_add_test(system_failure_e2e tests/system/test_autonomous_failure_e2e.c)
    target_link_libraries(system_failure_e2e PRIVATE pthread)
    add_executable(stress_agent_loop tests/stress/test_agent_loop_stress.c)
    target_link_libraries(stress_agent_loop PRIVATE aegis_core pthread)
    add_test(NAME stress_agent_loop COMMAND stress_agent_loop)
    add_executable(integration_cli tests/integration/test_cli.c)
    add_test(NAME integration_cli COMMAND integration_cli)
endif()

# ── Mock plugin ─────────────────────────────────────────────────────────
add_library(mock_plugin SHARED tests/plugin/plugin_mock.c)
target_include_directories(mock_plugin PRIVATE ${PROJECT_SOURCE_DIR}/include
                                                ${PROJECT_SOURCE_DIR}/src/internal)
target_link_libraries(mock_plugin PRIVATE aegis_core)
set_target_properties(mock_plugin PROPERTIES
    LIBRARY_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/tests/plugin"
)

# ── Benchmarks ──────────────────────────────────────────────────────────
if(AEGIS_BUILD_BENCH)
    find_package(benchmark QUIET)
    if(NOT benchmark_FOUND)
        message(STATUS "google/benchmark not found; skipping benchmarks")
    else()
        add_executable(bench_scheduler benchmarks/bench_scheduler.c)
        target_link_libraries(bench_scheduler PRIVATE aegis_core benchmark::benchmark)
        aegis_set_warnings(bench_scheduler)
    endif()
endif()
